# Exploratory Data Analysis and Insights on Air Quality Using Pandas

### Beginner-to-Intermediate Pandas Practice Notebook

This notebook is designed for students who are learning how to clean and explore environmental time-series data using **Pandas**.

The exercises begin with basic DataFrame operations and gradually introduce:

- Loading and inspecting a CSV file
- Identifying and handling missing values
- Combining date and time columns
- Selecting, filtering, and sorting observations
- Calculating descriptive statistics
- Grouping records by month and hour
- Creating time-based and categorical columns
- Examining correlations
- Creating basic time-series visualizations
- Exporting cleaned data

## About the Dataset

The **AirQuality.csv** dataset contains **9,357 hourly observations** recorded by an air-quality monitoring device in an Italian city from March 2004 to April 2005.

It contains **15 columns**:

| Column | Description |
|---|---|
| `date`, `time` | Date and time of the observation |
| `co_gt` | Reference carbon monoxide concentration |
| `pt08_s1_co` | Sensor response associated with carbon monoxide |
| `nmhc_gt` | Reference non-methane hydrocarbon concentration |
| `benzene_gt` | Reference benzene concentration |
| `pt08_s2_nmhc` | Sensor response associated with non-methane hydrocarbons |
| `nox_gt` | Reference nitrogen oxides concentration |
| `pt08_s3_nox` | Sensor response associated with nitrogen oxides |
| `no2_gt` | Reference nitrogen dioxide concentration |
| `pt08_s4_no2` | Sensor response associated with nitrogen dioxide |
| `pt08_s5_o3` | Sensor response associated with ozone |
| `temperature_c` | Temperature in degrees Celsius |
| `relative_humidity` | Relative humidity percentage |
| `absolute_humidity` | Absolute humidity |

### Important Observation

The original data uses `-200` to represent missing readings. These markers have been converted to standard blank CSV values so Pandas will recognize them as `NaN`. The source's decimal commas and dotted time values were also converted into standard formats without changing the measurements.

Some pollutant columns contain many missing values. For this assignment, `df_clean` will remove only rows missing the three weather measurements, while Pandas will ignore remaining missing values during most calculations.

**Source:** [UCI Machine Learning Repository](https://archive.ics.uci.edu/dataset/360/air+quality)  
**License:** CC BY 4.0 for research use; review the repository terms before other uses.

## Learning Goal

By completing this assignment, you will practice a complete beginner-to-intermediate Pandas workflow. You will handle incomplete sensor data, create timestamps, compare measurements across months and hours, and visualize changes over time.

## 1. Loading and Understanding the Dataset

### Question 1
Import the Pandas library using the alias `pd` and read **AirQuality.csv** into a DataFrame named `df`.

In [2]:
import pandas as pd
df =pd.read_csv('AirQuality.csv' ,na_values = -200)


# if we dont mention na_values then it will consider -200 as a valid value and will not treat it as NaN. By specifying na_values=-200, we are telling pandas to treat -200 as a missing value (NaN) in the DataFrame. This is important for data cleaning and analysis, as it allows us to handle missing data appropriately.

# for later replacement of -200 with NaN, we can use the following line of code:
# df.replace(-200, float("nan"), inplace=True)

### Question 2
Display the first **5 rows** of the dataset.

In [3]:
df.head()

,date,time,co_gt,pt08_s1_co,nmhc_gt,benzene_gt,pt08_s2_nmhc,nox_gt,pt08_s3_nox,no2_gt,pt08_s4_no2,pt08_s5_o3,temperature_c,relative_humidity,absolute_humidity
0,10/03/2004,18:00:00,2.6,1360.0,150.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578
1,10/03/2004,19:00:00,2.0,1292.0,112.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255
2,10/03/2004,20:00:00,2.2,1402.0,88.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502
3,10/03/2004,21:00:00,2.2,1376.0,80.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867
4,10/03/2004,22:00:00,1.6,1272.0,51.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888

### Question 3
Display the last **5 rows** of the dataset.

In [4]:
df.tail()

,date,time,co_gt,pt08_s1_co,nmhc_gt,benzene_gt,pt08_s2_nmhc,nox_gt,pt08_s3_nox,no2_gt,pt08_s4_no2,pt08_s5_o3,temperature_c,relative_humidity,absolute_humidity
9352,04/04/2005,10:00:00,3.1,1314.0,NaN,13.5,1101.0,472.0,539.0,190.0,1374.0,1729.0,21.9,29.3,0.7568
9353,04/04/2005,11:00:00,2.4,1163.0,NaN,11.4,1027.0,353.0,604.0,179.0,1264.0,1269.0,24.3,23.7,0.7119
9354,04/04/2005,12:00:00,2.4,1142.0,NaN,12.4,1063.0,293.0,603.0,175.0,1241.0,1092.0,26.9,18.3,0.6406
9355,04/04/2005,13:00:00,2.1,1003.0,NaN,9.5,961.0,235.0,702.0,156.0,1041.0,770.0,28.3,13.5,0.5139
9356,04/04/2005,14:00:00,2.2,1071.0,NaN,11.9,1047.0,265.0,654.0,168.0,1129.0,816.0,28.5,13.1,0.5028

### Question 4
Find the total number of **rows and columns** in the dataset.

In [5]:
print('Rows :',df.shape[0])
print('Columns :',df.shape[1])

Rows : 9357
Columns : 15

### Question 5
Display all the **column names** in the dataset.

In [6]:
df.columns

Index(['date', 'time', 'co_gt', 'pt08_s1_co', 'nmhc_gt', 'benzene_gt',
       'pt08_s2_nmhc', 'nox_gt', 'pt08_s3_nox', 'no2_gt', 'pt08_s4_no2',
       'pt08_s5_o3', 'temperature_c', 'relative_humidity',
       'absolute_humidity'],
      dtype='object')

### Question 6
Display the **data type of each column**.

In [7]:
df.dtypes

date                  object
time                  object
co_gt                float64
pt08_s1_co           float64
nmhc_gt              float64
benzene_gt           float64
pt08_s2_nmhc         float64
nox_gt               float64
pt08_s3_nox          float64
no2_gt               float64
pt08_s4_no2          float64
pt08_s5_o3           float64
temperature_c        float64
relative_humidity    float64
absolute_humidity    float64
dtype: object

### Question 7
Display a complete summary of the DataFrame using `info()`.

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9357 entries, 0 to 9356
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               9357 non-null   object
 1   time               9357 non-null   object
 2   co_gt              7674 non-null   float64
 3   pt08_s1_co         8991 non-null   float64
 4   nmhc_gt            914 non-null    float64
 5   benzene_gt         8991 non-null   float64
 6   pt08_s2_nmhc       8991 non-null   float64
 7   nox_gt             7718 non-null   float64
 8   pt08_s3_nox        8991 non-null   float64
 9   no2_gt             7715 non-null   float64
 10  pt08_s4_no2        8991 non-null   float64
 11  pt08_s5_o3         8991 non-null   float64
 12  temperature_c      8991 non-null   float64
 13  relative_humidity  8991 non-null   float64
 14  absolute_humidity  8991 non-null   float64
dtypes: float64(13), object(2)
memory usage: 1.1+ MB

## 2. Missing Values and Date-Time Preparation

### Question 8
Display the number of **missing values in each column**.

In [9]:
df.isna().sum()

date                    0
time                    0
co_gt                1683
pt08_s1_co            366
nmhc_gt              8443
benzene_gt            366
pt08_s2_nmhc          366
nox_gt               1639
pt08_s3_nox           366
no2_gt               1642
pt08_s4_no2           366
pt08_s5_o3            366
temperature_c         366
relative_humidity     366
absolute_humidity     366
dtype: int64

### Question 9
Calculate the **total number of missing values** in the entire DataFrame.

In [10]:
df.isna().sum().sum()

np.int64(16701)

### Question 10
Display every row that contains **at least one missing value**.

In [12]:
print(df[df.isnull().any(axis=1)])

            date      time  co_gt  pt08_s1_co  nmhc_gt  benzene_gt  \
9     11/03/2004  03:00:00    0.6      1010.0     19.0         1.7
10    11/03/2004  04:00:00    NaN      1011.0     14.0         1.3
33    12/03/2004  03:00:00    0.8       889.0     21.0         1.9
34    12/03/2004  04:00:00    NaN       831.0     10.0         1.1
39    12/03/2004  09:00:00    NaN      1545.0      NaN        22.1
...          ...       ...    ...         ...      ...         ...
9352  04/04/2005  10:00:00    3.1      1314.0      NaN        13.5
9353  04/04/2005  11:00:00    2.4      1163.0      NaN        11.4
9354  04/04/2005  12:00:00    2.4      1142.0      NaN        12.4
9355  04/04/2005  13:00:00    2.1      1003.0      NaN         9.5
9356  04/04/2005  14:00:00    2.2      1071.0      NaN        11.9

      pt08_s2_nmhc  nox_gt  pt08_s3_nox  no2_gt  pt08_s4_no2  pt08_s5_o3  \
9            561.0     NaN       1705.0     NaN       1235.0       501.0
10           527.0    21.0       1818.0    34.0       1197.0       445.0
33           574.0     NaN       1680.0     NaN       1187.0       512.0
34           506.0    21.0       1893.0    32.0       1134.0       384.0
39          1353.0     NaN        767.0     NaN       2058.0      1588.0
...            ...     ...          ...     ...          ...         ...
9352        1101.0   472.0        539.0   190.0       1374.0      1729.0
9353        1027.0   353.0        604.0   179.0       1264.0      1269.0
9354        1063.0   293.0        603.0   175.0       1241.0      1092.0
9355         961.0   235.0        702.0   156.0       1041.0       770.0
9356        1047.0   265.0        654.0   168.0       1129.0       816.0

      temperature_c  relative_humidity  absolute_humidity
9              10.3               60.2             0.7517
10             10.1               60.5             0.7465
33              7.0               62.3             0.6261
34              6.1               65.9             0.6248
39              9.2               56.2             0.6561
...             ...                ...                ...
9352           21.9               29.3             0.7568
9353           24.3               23.7             0.7119
9354           26.9               18.3             0.6406
9355           28.3               13.5             0.5139
9356           28.5               13.1             0.5028

[8530 rows x 15 columns]

### Question 11
Create a DataFrame named `df_clean` by removing rows missing `temperature_c`, `relative_humidity`, or `absolute_humidity`. Display its shape.

In [13]:
df_clean = df.dropna(subset=["temperature_c", "relative_humidity", "absolute_humidity"])

print(df_clean.shape)

(8991, 15)

### Question 12
Combine the `date` and `time` columns into a new datetime column named **datetime** using `pd.to_datetime()` with `dayfirst=True`.

In [15]:
df['datetime'] =pd.to_datetime(df['date'] + " "+ df['time'] , dayfirst=True)

print(df[['date' ,'time','datetime']].head())

         date      time            datetime
0  10/03/2004  18:00:00 2004-03-10 18:00:00
1  10/03/2004  19:00:00 2004-03-10 19:00:00
2  10/03/2004  20:00:00 2004-03-10 20:00:00
3  10/03/2004  21:00:00 2004-03-10 21:00:00
4  10/03/2004  22:00:00 2004-03-10 22:00:00

## 3. Selecting Rows and Columns

### Question 13
Select and display only the **temperature_c** column from `df_clean`.

In [16]:
df_clean['temperature_c']

0       13.6
1       13.3
2       11.9
3       11.0
4       11.2
        ...
9352    21.9
9353    24.3
9354    26.9
9355    28.3
9356    28.5
Name: temperature_c, Length: 8991, dtype: float64

### Question 14
Select and display the **datetime, co_gt, nox_gt, no2_gt, temperature_c, and relative_humidity** columns.

In [18]:
df[['datetime','co_gt','nox_gt','no2_gt','temperature_c','relative_humidity']]

,datetime,co_gt,nox_gt,no2_gt,temperature_c,relative_humidity
0,2004-03-10 18:00:00,2.6,166.0,113.0,13.6,48.9
1,2004-03-10 19:00:00,2.0,103.0,92.0,13.3,47.7
2,2004-03-10 20:00:00,2.2,131.0,114.0,11.9,54.0
3,2004-03-10 21:00:00,2.2,172.0,122.0,11.0,60.0
4,2004-03-10 22:00:00,1.6,131.0,116.0,11.2,59.6
...,...,...,...,...,...,...
9352,2005-04-04 10:00:00,3.1,472.0,190.0,21.9,29.3
9353,2005-04-04 11:00:00,2.4,353.0,179.0,24.3,23.7
9354,2005-04-04 12:00:00,2.4,293.0,175.0,26.9,18.3
9355,2005-04-04 13:00:00,2.1,235.0,156.0,28.3,13.5
9356,2005-04-04 14:00:00,2.2,265.0,168.0,28.5,13.1

### Question 15
Using `iloc`, display the first **5 rows and first 6 columns**.

In [19]:
df.iloc[:5,:6]

         date      time  co_gt  pt08_s1_co  nmhc_gt  benzene_gt
0  10/03/2004  18:00:00    2.6      1360.0    150.0        11.9
1  10/03/2004  19:00:00    2.0      1292.0    112.0         9.4
2  10/03/2004  20:00:00    2.2      1402.0     88.0         9.0
3  10/03/2004  21:00:00    2.2      1376.0     80.0         9.2
4  10/03/2004  22:00:00    1.6      1272.0     51.0         6.5

### Question 16
Using `loc`, display rows **10 to 15** for the columns **datetime, co_gt, benzene_gt, temperature_c, and relative_humidity**.

In [20]:
df.loc[10:15,['datetime', 'co_gt', 'benzene_gt','temperature_c', 'relative_humidity']]

              datetime  co_gt  benzene_gt  temperature_c  relative_humidity
10 2004-03-11 04:00:00    NaN         1.3           10.1               60.5
11 2004-03-11 05:00:00    0.7         1.1           11.0               56.2
12 2004-03-11 06:00:00    0.7         1.6           10.5               58.1
13 2004-03-11 07:00:00    1.1         3.2           10.2               59.6
14 2004-03-11 08:00:00    2.0         8.0           10.8               57.4
15 2004-03-11 09:00:00    2.2         9.5           10.5               60.6

## 4. Descriptive Statistics and Measurement Coverage

### Question 17
Display descriptive statistics for the numeric columns using `describe()`.

In [21]:
df.describe()

,co_gt,pt08_s1_co,nmhc_gt,benzene_gt,pt08_s2_nmhc,nox_gt,pt08_s3_nox,no2_gt,pt08_s4_no2,pt08_s5_o3,temperature_c,relative_humidity,absolute_humidity,datetime
count,7674.000000,8991.000000,914.000000,8991.000000,8991.000000,7718.000000,8991.000000,7715.000000,8991.000000,8991.000000,8991.000000,8991.000000,8991.000000,9357
mean,2.152750,1099.833166,218.811816,10.083105,939.153376,246.896735,835.493605,113.091251,1456.264598,1022.906128,18.317829,49.234201,1.025530,2004-09-21 16:00:00
min,0.100000,647.000000,7.000000,0.100000,383.000000,2.000000,322.000000,2.000000,551.000000,221.000000,-1.900000,9.200000,0.184700,2004-03-10 18:00:00
25%,1.100000,937.000000,67.000000,4.400000,734.500000,98.000000,658.000000,78.000000,1227.000000,731.500000,11.800000,35.800000,0.736800,2004-06-16 05:00:00
50%,1.800000,1063.000000,150.000000,8.200000,909.000000,180.000000,806.000000,109.000000,1463.000000,963.000000,17.800000,49.600000,0.995400,2004-09-21 16:00:00
75%,2.900000,1231.000000,297.000000,14.000000,1116.000000,326.000000,969.500000,142.000000,1674.000000,1273.500000,24.400000,62.500000,1.313700,2004-12-28 03:00:00
max,11.900000,2040.000000,1189.000000,63.700000,2214.000000,1479.000000,2683.000000,340.000000,2775.000000,2523.000000,44.600000,88.700000,2.231000,2005-04-04 14:00:00
std,1.453252,217.080037,204.459921,7.449820,266.831429,212.979168,256.817320,48.370108,346.206794,398.484288,8.832116,17.316892,0.403813,NaN

### Question 18
Display the **earliest and latest datetime values** in `df_clean`.

In [23]:
df_clean["datetime"] = df.loc[df_clean.index, "datetime"]
print("Earliest datetime:", df_clean["datetime"].min())
print("Latest datetime:", df_clean["datetime"].max())

Earliest datetime: 2004-03-10 18:00:00
Latest datetime: 2005-04-04 14:00:00

C:\Users\sumitshinde\AppData\Local\Temp\ipykernel_1564\2454406961.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean["datetime"] = df.loc[df_clean.index, "datetime"]

### Question 19
Find the **minimum, maximum, and mean temperature**.

In [24]:
df['temperature_c'].agg(['min','max','mean'])

min     -1.900000
max     44.600000
mean    18.317829
Name: temperature_c, dtype: float64

### Question 20
Calculate the **mean relative humidity**.

In [25]:
df['relative_humidity'].mean()

np.float64(49.2342008675342)

### Question 21
Count the number of non-missing readings in the **co_gt** and **nmhc_gt** columns.

In [26]:
print(df[["co_gt", "nmhc_gt"]].count())

co_gt      7674
nmhc_gt     914
dtype: int64

### Question 22
Display the record with the **highest no2_gt value**.

In [27]:
print(df.loc[df["no2_gt"].idxmax()])

date                          11/02/2005
time                            16:00:00
co_gt                                7.1
pt08_s1_co                           NaN
nmhc_gt                              NaN
benzene_gt                           NaN
pt08_s2_nmhc                         NaN
nox_gt                            1218.0
pt08_s3_nox                          NaN
no2_gt                             340.0
pt08_s4_no2                          NaN
pt08_s5_o3                           NaN
temperature_c                        NaN
relative_humidity                    NaN
absolute_humidity                    NaN
datetime             2005-02-11 16:00:00
Name: 8110, dtype: object

## 5. Filtering and Sorting

### Question 23
Display all observations where **temperature_c is greater than 30°C**.

### Question 24
Display observations where **relative_humidity is greater than 80%**.

### Question 25
Display observations where **co_gt is greater than 5**.

### Question 26
Using `query()`, display observations where **benzene_gt is greater than 20** and **nox_gt is greater than 200**.

### Question 27
Sort `df_clean` by **temperature_c in descending order** and display the first 10 rows.

### Question 28
Display the **5 observations with the highest no2_gt readings**.

## 6. Grouping and Aggregation

### Question 29
Calculate the **average temperature for each month number** using the `datetime` column.

### Question 30
Calculate the **average co_gt reading for each hour of the day**.

### Question 31
Calculate the monthly averages of **co_gt, benzene_gt, nox_gt, and no2_gt**.

### Question 32
For each hour of the day, calculate the **minimum, maximum, and mean temperature** using `agg()`.

### Question 33
Determine which month number has the **highest average no2_gt reading**.

## 7. Creating and Modifying Columns

### Question 34
Create a new column named **month** from `datetime` using the `.dt` accessor.

### Question 35
Create a new column named **hour** from `datetime` using the `.dt` accessor.

### Question 36
Create a column named **temperature_level** using `apply()` with a `lambda` function. Store `Warm` when `temperature_c` is greater than or equal to 25; otherwise store `Cool`.

## 8. Correlation, Visualization, and Export

### Question 37
Create a correlation matrix for **co_gt, benzene_gt, nox_gt, no2_gt, temperature_c, and relative_humidity**.

### Question 38
Create a **line chart** showing the daily average temperature over time.

### Question 39
Create a **histogram** of the non-missing `co_gt` readings with an appropriate title and axis labels.

### Question 40
Save `df_clean` as **AirQuality_Cleaned.csv** using `to_csv()` without saving the index.

## End of Practice

Try to solve each question independently before checking any reference material.

The main goal is to become comfortable with incomplete time-series data, datetime operations, grouped summaries, and basic environmental visualizations before moving to forecasting or predictive modeling.